name: meld_graph
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.10.0
  - cpuonly
  - pytest=7.0.1
  - jupyterlab=3.2.9
  - h5py=3.6.0
  - fpdf=1.7.2
  - scikit-image=0.18
  - pip=23.3.1
  - libopenblas=0.3.15
  - clang_osx-arm64 
  - clangxx_osx-arm64 
  - gfortran_osx-arm64
  - libtiff
  - pip:
    - potpourri3d==0.0.6
    - captum==0.6.0
    - pandas==1.4.1
    - matplotlib==3.5.1
    - neuroCombat==0.2.12
    - nibabel==3.2.2
    - nilearn==0.10.2
    - patsy==0.5.4
    - progressbar2==4.2.0
    - statsmodels==0.14.1
    - seaborn==0.11.0
    - matplotlib_surface_plotting==0.10
    - numpy==1.22.0
    - pytest==6.2.3
    - torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cpu.html
    # - torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu111.html
    - torch-geometric==2.4.0 #-f https://data.pyg.org/whl/torch-1.10.0+cpu.html
    # - torchvision==0.11.2 # needed for fastsurfer
    # - lapy==0.6.0 # needed for fastsurfer
    # - SimpleITK==2.1.1 # needed for fastsurfer
    - pybids==0.16.4
# variables:
#   - MACOSX_DEPLOYMENT_TARGET: "12.5"
#   - CC: clang
#   - CXX: clang++
