name: meld_graph
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.10.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.1
  - pytest
  - jupyterlab
  - pip
  - pip:
    - potpourri3d

